language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-8
  - pip install -r requirements.txt
script: make
