language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq clang
  - pip install -r requirements-travis.txt
  - CC=clang pip install csvmonkey==0.0.5
script: make
